### Health Check
GET http://localhost:3000/

### Listar transações
GET http://localhost:3000/transactions

### Criar transação (receita)
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "title": "Salário",
  "amount": 3000,
  "type": "income",
  "categoryId": 3
}

### Criar transação (despesa)
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "title": "Mercado",
  "amount": 450,
  "type": "expense",
  "categoryId": 5
}

### Buscar transação por ID
GET http://localhost:3000/transactions/1

### Atualizar transação
PUT http://localhost:3000/transactions/1
Content-Type: application/json

{
  "title": "Salário atualizado",
  "amount": 3500
}

### Deletar transação
DELETE http://localhost:3000/transactions/1


### ========== RESUMO FINANCEIRO ==========

### Ver resumo
GET http://localhost:3000/transactions/summary



### ========== CATEGORIAS ==========

### Criar categoria
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Alimentação"
}

### Listar categorias
GET http://localhost:3000/categories

### Buscar categoria por ID
GET http://localhost:3000/categories/1

### Atualizar categoria
PUT http://localhost:3000/categories/1
Content-Type: application/json

{
  "name": "Alimentação e Bebidas"
}

### Deletar categoria
DELETE http://localhost:3000/categories/1