### Health Check
GET http://localhost:3000/

### Listar transações
GET http://localhost:3000/transactions

### Criar transação (receita)
POST http://localhost:3000/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjb2RlY0BlbWFpbC5jb20iLCJpYXQiOjE3NzQ0Nzg4NjYsImV4cCI6MTc3NTA4MzY2Nn0.GOdPrdYytIatA7HBrATQUeO9K_-munCEqqEUmmVuE6c

{
  "title": "Salário",
  "amount": 3000,
  "type": "income",
  "categoryId": 3
}

### Criar transação (despesa)
POST http://localhost:3000/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjb2RlY0BlbWFpbC5jb20iLCJpYXQiOjE3NzQ0Nzg4NjYsImV4cCI6MTc3NTA4MzY2Nn0.GOdPrdYytIatA7HBrATQUeO9K_-munCEqqEUmmVuE6c

{
  "title": "Mercado",
  "amount": 450,
  "type": "expense",
  "categoryId": 5
}

### Buscar transação por ID
GET http://localhost:3000/transactions/1

### Atualizar transação
PUT http://localhost:3000/transactions/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjb2RlY0BlbWFpbC5jb20iLCJpYXQiOjE3NzQ0Nzg4NjYsImV4cCI6MTc3NTA4MzY2Nn0.GOdPrdYytIatA7HBrATQUeO9K_-munCEqqEUmmVuE6c

{
  "title": "Salário atualizado",
  "amount": 3500
}

### Deletar transação
DELETE http://localhost:3000/transactions/1


### ========== RESUMO FINANCEIRO ==========

### Ver resumo
GET http://localhost:3000/transactions/summary



### ========== CATEGORIAS ==========

### Criar categoria
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Alimentação"
}

### Listar categorias
GET http://localhost:3000/categories

### Buscar categoria por ID
GET http://localhost:3000/categories/1

### Atualizar categoria
PUT http://localhost:3000/categories/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjb2RlY0BlbWFpbC5jb20iLCJpYXQiOjE3NzQ0Nzg4NjYsImV4cCI6MTc3NTA4MzY2Nn0.GOdPrdYytIatA7HBrATQUeO9K_-munCEqqEUmmVuE6c

{
  "name": "Bebidas"
}

### Deletar categoria
DELETE http://localhost:3000/categories/1



### ========== AUTENTICAÇÃO ==========

### Registrar usuário
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Codec2",
  "email": "pecinallipoker@gmail.com",
  "password": "123456"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "pecinallimarketing@gmail.com",
  "password": "novaSenha123"
}

### ========== ROTAS PROTEGIDAS (cole o token do login) ==========

### Listar transações (com token)
GET http://localhost:3000/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjb2RlY0BlbWFpbC5jb20iLCJpYXQiOjE3NzQ0Nzg4NjYsImV4cCI6MTc3NTA4MzY2Nn0.GOdPrdYytIatA7HBrATQUeO9K_-munCEqqEUmmVuE6c

### Criar transação (com token)
POST http://localhost:3000/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjb2RlY0BlbWFpbC5jb20iLCJpYXQiOjE3NzQ0Nzg4NjYsImV4cCI6MTc3NTA4MzY2Nn0.GOdPrdYytIatA7HBrATQUeO9K_-munCEqqEUmmVuE6c

{
  "title": "Emprestimo",
  "amount": 10,
  "type": "income"
}

### Teste sem token (deve dar 401)
GET http://localhost:3000/transactions


### Listar histórico de ações
GET http://localhost:3000/activity
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjb2RlY0BlbWFpbC5jb20iLCJpYXQiOjE3NzQ1NTMyNzAsImV4cCI6MTc3NTE1ODA3MH0.6AUxjSmomG9F3ZcikDckA-5BjQguYP0tplu3eMLx9uM

### Resumo sem filtro
GET http://localhost:3000/transactions/summary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjb2RlY0BlbWFpbC5jb20iLCJpYXQiOjE3NzQ1NTMyNzAsImV4cCI6MTc3NTE1ODA3MH0.6AUxjSmomG9F3ZcikDckA-5BjQguYP0tplu3eMLx9uM

### Resumo com data
GET http://localhost:3000/transactions/summary?dateFrom=2026-03-25&dateTo=2026-03-26
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJjb2RlY0BlbWFpbC5jb20iLCJpYXQiOjE3NzQ1NTMyNzAsImV4cCI6MTc3NTE1ODA3MH0.6AUxjSmomG9F3ZcikDckA-5BjQguYP0tplu3eMLx9uM


### Forgot Password
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "email": "pecinallimarketing@gmail.com"
}

### Reset Password
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "token": "41f91c39046076297665052761e737ed535c4c7cce918b12c8aee2e736bb090d",
  "password": "novaSenha123"
}